import pygame as pg

# SCREEN
SCREEN_W, SCREEN_H = 600, 600
SOURCE = (0,0)
CAPTION = 'Funny Quest'

# DATA CONFIG
DATA = 'data'
CONFIG = 'config/config.json'
SCORES_CSV = 'scores.csv'

# INSTANCES
IMAGES = 'images'
BACKGROUNDS = 'backgrounds'
QUESTIONS = 'questions'
HOME = 'home'
SETTINGS = 'settings'
SCORES = 'scores'
STAGES = 'stages'
AVENGERS = 'avengers'
SIMPSONS = 'simpsons'
STARWARS = 'starwars'
GAMEOVER = 'gameover'
USERNAME = 'username'

# GENERIC KEYS
POSITION = 'position'
NAME = 'name'
DATE = 'date'
FILE = 'file'
ID = 'id'
X = 'x'
Y = 'y'
IMAGE = 'image'
QUESTION = 'question'
ANSWER = 'answer'
BUTTONS = 'buttons'
LABELS = 'labels'
RENDER = 'render'
OPTION = 'option'

# FILES
R = 'r'
A = 'a'
UTF = 'utf-8'

# DATES
STANDAR_FORMAT = f'%Y-%m-%d'
FORMAT = f'%d-%m-%y'

# QUESTIONS
AVENGERS_QUESTIONS = 'avengers_questions'
SIMPSONS_QUESTIONS = 'simpsons_questions'
STARWARS_QUESTIONS = 'starwars_questions'

# INTEGERS
INT_0 = 0
INT_1 = 1
INT_2 = 2
INT_3 = 3
INT_4 = 4
INT_5 = 5
INT_10 = 10
INT_45 = 45
INT_48 = 48
INT_57 = 57

# INTEGER VALUES
FPS = 20
MS_1000 = 1000
REWARD = 100
PENALTY = 25
QUEST_INIT = 0
LIVES_INIT = 3
SCORE_INIT = 0
PLAY_TIME = 10
GAMEOVER_TIME = 4
GAMEOVER_DELAY = 2
LEN_MAX_BLOCK = 24
USERNAME_LEN_MAX = 8
USERNAME_LEN_MIN = 3

# QUESTION AND OPTIONS INIT POSITIONS
Y_INIT_QUEST = 130
Y_INIT_OPT = 300
X_INIT_OPT = 125
Y_VAR = 40

# USERNAME INIT POSITIONS
Y_USERNAME_SCORE = 100
Y_USERNAME = 310
Y_WARNING = 400

# SCORES TABLE INIT POSITIONS
X_POS = 85
X_NAME = 100
X_SCORE = 365
X_DATE = 390
Y_INIT_TABLE = 145
Y_VAR_TABLE = 34

# GENERIC STRINGS
VOID_STR = ''
SPACE_STR = ' '
HYPHEN_STR = '_'
COMMA_STR = ','
ASTERISK_STR = '*'

# EVENTS
EVENT_1000MS = pg.USEREVENT

# BUTTONS
PLAY_BUTTON = 'play_button'
SETTINGS_BUTTON = 'settings_button'
SCORES_BUTTON = 'scores_button'
HOME_BUTTONS = [PLAY_BUTTON, SETTINGS_BUTTON, SCORES_BUTTON]
HOME_BUTTON = 'home_button'
PASS_BUTTON = 'pass_button'
ENTER_BUTTON = 'enter_button'
AVENGERS_BUTTON = 'avengers_button'
SIMPSONS_BUTTON = 'simpsons_button'
STARWARS_BUTTON = 'starwars_button'
STAGES_BUTTONS = [HOME_BUTTON, AVENGERS_BUTTON, SIMPSONS_BUTTON, STARWARS_BUTTON]
GAME_BUTTONS = [PASS_BUTTON]
SCORES_BUTTONS = [HOME_BUTTON]
USERNAME_BUTTONS = [ENTER_BUTTON]

# LABELS
LIVES = 'lives'
LIVES_RENDER = 'lives_render'
TIME = 'time'
TIME_RENDER = 'time_render'
SCORE = 'score'
SCORE_RENDER = 'score_render'

# TEXT
FONT_COURIER = 'Courier New'
FONT_SEGOE = 'Segoe Print'
FONT_MV_BOLI = 'MV Boli'
FONT_SIZE_QUEST = 28
FONT_SIZE_OPT = 24
FONT_SIZE_LAB = 20
FONT_SIZE_SCORES = 25
FONT_SIZE_USERNAME = 48
FONT_SIZE_SCORE = 60
FONT_SIZE_WARNING = 24
BOLD_ENABLE = True
OPTIONS = [1,2,3,4]
QUESTION_RENDER = 'question_render'
OPTIONS_RENDER = 'options_render'

# TABLE HEADERS
TABLE_HEADERS = [POSITION, NAME, SCORE, DATE]

# COLORS
YELLOW = (230,233,0)
BLUE = (10,0,204)
WHITE = (255,255,255)
AQUA = (0,190,200)
VIOLET = (145,25,255)
RED = (255,0,0)
GREEN = (0,255,0)

# WARNINGS
WARNING_MIN_MAX = 'Use at least 3 characters and 8 as maximum'
WARNING_USE_LETTERS = 'Use only letters'
WARNING_NAME_OK = 'User name ok'